name: Maven deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java & Maven
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - name: Run Maven
        env:
          DEPLOYMENT_SETTINGS_XML: ${{ secrets.DEPLOYMENT_SETTINGS_XML }}
        run: |
          echo $DEPLOYMENT_SETTINGS_XML > ci_settings.xml
          mvn --batch-mode --no-transfer-progress --update-snapshots deploy -s ci_settings.xml ${{ secrets.DEPLOYMENT_CLI_OPTIONS }}
